version: 2.1

orbs:
  # The maven orb contains a set of prepackaged circleci configuration you can use repeatedly in your configurations files
  # Orb commands and jobs help you with common scripting around a language/tool
  # so you dont have to copy and paste it everywhere.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/maven
  maven: circleci/maven@1.3

executors:
  openjdk11:
    docker:
      - image: cimg/openjdk:11.0
      - image: cimg/postgres:14.1
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: cfd

parameters:
  run_echo:
    type: boolean
    default: false

workflows:
  say-hi:
    when: <<pipeline.parameters.run_echo >>
    jobs:
      - echo-message
  run-test:
    jobs:
      - maven-test:
          filters:
              tags:
                only: /.*/
    

jobs:
  echo-message:
    docker:
      - image: cimg/node:17.2.0 
    steps: 
    - run: echo "Saying hi"
  maven-test:
    executor: openjdk11
    steps:
      - run:
          name: Install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
